use different styling options for clear_button and clear_tag_button
maxmarcon/live_select pull request #76
Opened 2024-07-12 08:44 UTC by Munksgaard

I think this is enough.

Fixes: #75

2024-07-12 12:29 UTC, maxmarcon commented
Thank you for this! I will look into it as soon as a I find some time (early next week probably)

2024-07-13 19:37 UTC, maxmarcon requested changes
Looks great! I suggested a few changes that I think will improve the quality

2024-07-13 19:37 UTC, maxmarcon commented on test/support/helpers.ex
Let's also add:
```
    clear_button: :clear_button_extra_class,
    clear_tag_button: :clear_tag_button_extra_class,
```

to `@extend_class_option` so we test also class extension. I tested locally and some things may break, the class names need to be reordered. Try to fix it, if you're stuck, I can help

2024-07-13 20:01 UTC, Munksgaard commented on lib/live_select.ex
> +  @styling_options ~w(active_option_class available_option_class clear_button_class clear_tag_button_class container_class container_extra_class dropdown_class dropdown_extra_class option_class optio
Done in 48d24d4

2024-07-13 20:02 UTC, Munksgaard commented on test/support/helpers.ex
I've started this in 397a26a, but I'm still getting one test failure:

```
  1) test using both clear_button_class and clear_button_extra_class options raises (LiveSelect.ComponentTest)
     test/live_select/component_test.exs:503
     Expected exception RuntimeError but nothing was raised
     code: assert_raise(
     stacktrace:
       test/live_select/component_test.exs:504: (test)
```

Perhaps you can figure out how to fix it?

2024-07-14 11:03 UTC, maxmarcon commented on test/support/helpers.ex
yes, I fixed it :)

2024-07-14 11:03 UTC, maxmarcon commented
Thank you so much! 🚀

2024-07-14 11:03 UTC, merged

2024-07-14 11:04 UTC, Munksgaard commented
Thank you!